# Generated by Django 5.2.8 on 2025-11-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
